### PR TITLE
New card class

### PR DESCRIPTION
**Pull request by ELdER1cH**

### CODE REVIEW

**Comment by PsychicPenguin** [comment]
The card class as well as the idea for debugging ability make sense, although similarly to my issue with #5 the quiz.py will cause problems

**Comment by ELdER1cH** [comment]
> The card class as well as the idea for debugging ability make sense, although similarly to my issue with #5 the quiz.py will cause problems

Yeah I saw, that the debugging was more of a makeshift Version Since I searched for the error in the Questions 

And the Card Conzept is something we might have a look at in the future since the Array Approach is getting pretty difficult to manage scaling wise

**Comment by PsychicPenguin** [comment]
Yes, modularizing it like that makes sense in the long run, however i fear that instantiating a whole bunch of objects will not make it any more clear than an array. I agree it is an idea we should follow with the grand restructuring

**Comment by ELdER1cH** [comment]
> Yes, modularizing it like that makes sense in the long run, however i fear that instantiating a whole bunch of objects will not make it any more clear than an array. I agree it is an idea we should follow with the grand restructuring

Yes, I was more or less writing down the general approach but how we will structure it in the end idk

**Comment by PsychicPenguin** [comment]
I don't think that necessarily makes much sense, as we will likely change it many times as we decide our concrete approach...

**Comment by ELdER1cH** [comment]
> I don't think that necessarily makes much sense, as we will likely change it many times as we decide our concrete approach...

Yes I agree, I was just like YAY Lets do this I am motivated ... and then this happend ... I would just let this sit here and we will come back in the future

**Comment by PsychicPenguin** [comment]
Soooo... Deny?..😅

**Comment by ELdER1cH** [comment]
We will come back to it in the future

**Pull request closed without merging**
